[package]
name = "tl-auth"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = {workspace = true}
chrono = {workspace = true}
jsonwebtoken = {workspace = true}
rboot={path = "../rboot"}
sea-orm = {version = "2.0.0-rc.21", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"]}
tokio = { workspace = true }
serde = { workspace = true }
p256     = { version = "0.13", features = ["ecdsa", "pkcs8", "pem"] }
pem-rfc7468 = "1.0.0"
rand_core = "0.10.0-rc-3"
anyhow = {workspace = true}
# axum-jwt-auth = "0.6.2"
serde_json = { workspace=true }
axum-extra = { workspace=true}
headers = "0.4.1"
